- name: start docker service
  service: name="docker" state=restarted

- name: create dockerfile dir
  file: path="{{ consts.docker_path }}" state=directory owner=root group=root mode=0755

- name: check Dockerfile
  stat: path="{{ consts.docker_path }}/Dockerfile"
  register: Dockerfile
  changed_when: false

- name: set dockerfile
  template: src="Dockerfile.j2" dest="{{ consts.docker_path }}/Dockerfile"
            owner=root group=root mode=0644
  when: not Dockerfile.stat.exists

- name: set sshd.sh
  template: src="sshd.sh.j2" dest="{{ consts.docker_path }}/sshd.sh"
            owner=root group=root mode=0644
  when: not Dockerfile.stat.exists

- name: create docker image
  shell: docker build -t {{ consts.container_image }} .
         chdir="{{ consts.docker_path }}"
  when: not Dockerfile.stat.exists

