- name: start docker service
  service: name="docker" state="started"

- name: remove containers file
  file: path="{{ consts.containers_file }}" state=absent

- name: start containers
  start_container: image="{{ consts.container_image }}"
                   cfile="{{ consts.containers_file }}"
                   network="{{ networks.virtual[0] }}"
                   container="{{ item }}"
  with_items: node.containers
