- hosts: vnet1
  sudo: yes
  vars_files:
    - vars/consts.yml
    - vars/networks.yml
    - vars/vnet1.yml
  roles:
    - docker/start_containers

- hosts: vnet2
  sudo: yes
  vars_files:
    - vars/consts.yml
    - vars/networks.yml
    - vars/vnet2.yml
  roles:
    - docker/start_containers

- hosts: vnet3
  sudo: yes
  vars_files:
    - vars/consts.yml
    - vars/networks.yml
    - vars/vnet3.yml
  roles:
    - docker/start_containers
