- name: check ifcfg-br0
  stat: path="/etc/sysconfig/network-scripts/ifcfg-br0"
  register: ifcfg_br0
  changed_when: false

- name: create ifcfg-br0
  template: src="ifcfg-br0.j2" dest="/etc/sysconfig/network-scripts/ifcfg-br0" 
            owner=root group=root mode=0644
  when: not ifcfg_br0.stat.exists

- name: remove original ifcfg-eth1
  file: path="/etc/sysconfig/network-scripts/ifcfg-eth1" state=absent
  when: not ifcfg_br0.stat.exists

- name: create ifcfg-eth1
  template: src="ifcfg-eth1.j2" dest="/etc/sysconfig/network-scripts/ifcfg-eth1" 
            owner=root group=root mode=0644
  when: not ifcfg_br0.stat.exists
  notify: restart network
