name: "vnet3"
virtual:
  name: "internal"
  nw_addr: "192.168.99.0"
  nw_mask: 24
containers:
  - name:           "container31"
    ip_addr:        "192.168.99.31"
    mac_addr:       "10:00:00:00:03:31"
    bridge_if:      "veth31b"
    container_if:   "veth31c"
    securigy_group: "sg-1"
  - name:           "container32"
    ip_addr:        "192.168.99.32"
    mac_addr:       "10:00:00:00:03:32"
    bridge_if:      "veth32b"
    container_if:   "veth32c"
    securigy_group: "sg-2"
  - name:           "container33"
    ip_addr:        "192.168.99.33"
    mac_addr:       "10:00:00:00:03:33"
    bridge_if:      "veth33b"
    container_if:   "veth33c"
    securigy_group: "sg-3"
